Now we need to set dev_server config to Rails.env.test
```
Error:
PagesControllerTest#test_it_mounts_components_from_the_dev_server:
RuntimeError: Failed to start dev server
    /home/travis/build/reactjs/react-rails/test/support/webpacker_helpers.rb:65:in `with_dev_server'
    /home/travis/build/reactjs/react-rails/test/react/rails/pages_controller_test.rb:32:in `block (2 levels) in <class:PagesControllerTest>'
```

Related to https://github.com/rails/webpacker/pull/1179